a= input(("Value of a : "))
b= input(("value of b : "))
print(a)
print(b)
print ("Input in string data type ==", a + b) # here 'a' and 'b' is in string datatype for addition need to typecast
print ("Input in without string data type ==", int (a) + int (b))
c= input ("enter your name :")
print (c)

i=int(input("Enter a value"))
j=float(input("Enter a value"))
print(i + j)
print(i - j)
print(i / j)
print(i * j)
print(i // j)
print(i ** j)
print(i % j)